# FROM mysql:latest

# ENV MYSQL_ROOT_PASSWORD = 2023

# COPY src/modules/db/database.sql /docker-entrypoint-initdb.d/ 

# RUN chmod 0444 /docker-entrypoint-initdb.d/database.sql

FROM rust:latest

RUN apt-get update && apt-get install -y default-libmysqlclient-dev

RUN rustup default nightly

WORKDIR /biblioteca_moraes

COPY . . 

EXPOSE 8000

CMD ["cargo", "run"]