[package]
name = "mem-view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contiguous-mem = "0.4.2"
mem_dbg = "0.1.3"
mem_dbg-derive = "0.1.2"
rusage = "0.0.1"
